#!/usr/bin/python
import pyconfuzzer
import os
import subprocess
import sys

if len(sys.argv) != 3:
    print "Usage: %s TAINTED_INPUT PROGRAM" % (sys.argv[0])
    sys.exit(-1)

if not os.path.isfile('confuzzer.so'):
    subprocess.call(['make'])

taintedInput = sys.argv[1]
program = sys.argv[2]

pyconfuzzer.run(program, [('FILE', taintedInput)])
